# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Backend

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        working-directory: ./Backend
        run: dotnet restore

      - name: Build
        working-directory: ./Backend
        run: dotnet build -c Release --no-restore

      - name: Publish
        working-directory: ./Backend
        run: dotnet publish -c Release --no-build

      - name: Checkout Test Data
        uses: actions/checkout@v3
        with:
          repository: "nam20485/mmm-test"
          ref: "master"
          path: "${{ vars.TEST_DATA_DIR_PATH }}"
          lfs: true          

      - name: Test
        # can't set working-directory for entire step b/c the TEST_DATA_DIR_PATH uses a relative path, 
        # which would place it under the Backend directory when it's really at the root of the repo
        #working-directory: ./Backend
        run: |
          cd ./Backend
          dotnet test -c Release --no-build --verbosity normal
        env:          
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TEST_DATA_DIR_PATH: ${{ vars.TEST_DATA_DIR_PATH }}      
