# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Backend

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies (linux-x64)
        working-directory: ./Backend
        run: dotnet restore

      - name: Build
        working-directory: ./Backend
        run: dotnet build -c Release --no-restore

      - name: Publish (linux-x64)
        working-directory: ./Backend
        run: dotnet publish -c Release --no-build --no-restore

      - name: Test
        working-directory: ./Backend
        run: dotnet test -c Release --no-build --verbosity normal
        env:          
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
